# Generated by Django 3.0.6 on 2020-06-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200609_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='uploadFile',
            new_name='video',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
