# Generated by Django 3.0.6 on 2020-06-23 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_auto_20200623_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, default='default.mp4', upload_to=''),
        ),
    ]
