# Generated by Django 3.0.6 on 2020-12-11 19:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_auto_20201005_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Mental', 'Mental'), ('Food', 'Food'), ('Sleep', 'Sleep'), ('Exercise', 'Exercise')], default=None, error_messages={'topic': 'Select at least one topic your post entails.'}, max_length=26),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
