# Generated by Django 3.0.6 on 2020-12-19 00:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0011_auto_20201211_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='likes',
            field=models.ManyToManyField(related_name='blogPosts', to=settings.AUTH_USER_MODEL),
        ),
    ]
