# Generated by Django 2.0.3 on 2019-05-03 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='firstName',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='healthdata',
            name='lastName',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
