# Generated by Django 2.0.3 on 2019-06-03 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190503_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthdata',
            name='author',
        ),
    ]
