# Generated by Django 2.0.3 on 2019-06-05 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20190605_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthdata',
            name='group',
            field=models.IntegerField(blank=True, choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True),
        ),
        migrations.AddField(
            model_name='healthdata',
            name='height',
            field=models.CharField(default='', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='often',
            field=models.CharField(choices=[('1-2', '1-2'), ('3-4', '3-4'), ('5+', '5+')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthdata',
            name='weight',
            field=models.CharField(default='', max_length=3),
            preserve_default=False,
        ),
    ]
