# Generated by Django 2.0.3 on 2019-06-05 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190605_0441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthdata',
            name='often',
            field=models.CharField(choices=[('1-2', '1-2'), ('3-4', '3-4'), ('5+', '5+')], max_length=3),
        ),
    ]
