# Generated by Django 2.0.3 on 2019-07-05 06:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0008_auto_20190605_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='General',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('thumb', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('location', models.CharField(max_length=100, null=True)),
                ('group', models.IntegerField(blank=True, choices=[(2, 2), (3, 3), (4, 4), (5, 5), (6, 6)], null=True)),
                ('often', models.CharField(choices=[('1-2', '1-2'), ('3-4', '3-4'), ('5+', '5+')], max_length=3)),
                ('author', models.ForeignKey(default=None, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unisex/Parody')], max_length=1)),
                ('age', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=4)),
                ('weight', models.CharField(max_length=3)),
                ('fit', models.CharField(blank=True, choices=[('B', 'beginner'), ('BtoI', 'between beginner and intermediate'), ('I', 'intermediate'), ('ItoA', 'between intermediate and advanced'), ('A', 'advanced')], max_length=1)),
                ('goal', models.CharField(blank=True, choices=[('L', 'Lose Weight'), ('M', 'Maintain'), ('B', 'Bulk')], max_length=1)),
                ('author', models.ForeignKey(default=None, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='healthdata',
            name='author',
        ),
        migrations.DeleteModel(
            name='HealthData',
        ),
    ]
