# Generated by Django 2.0.3 on 2019-07-05 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190705_0655'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='username',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='username',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='health',
            name='fit',
            field=models.CharField(blank=True, choices=[('B', 'beginner'), ('BtoI', 'between beginner and intermediate'), ('I', 'intermediate'), ('ItoA', 'between intermediate and advanced'), ('A', 'advanced')], max_length=100),
        ),
    ]
