# Generated by Django 2.0.3 on 2019-07-05 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20190705_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='health',
            name='first_name',
        ),
    ]
