# Generated by Django 2.0.3 on 2019-07-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20190705_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='goal',
            field=models.CharField(blank=True, choices=[('Lose Weight', 'Lose Weight'), ('Maintain', 'Maintain'), ('Bulk', 'Bulk')], max_length=1),
        ),
    ]
