# Generated by Django 2.0.3 on 2019-07-07 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20190707_0711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='username',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='health',
            old_name='username',
            new_name='name',
        ),
    ]
