# Generated by Django 2.0.3 on 2019-07-07 07:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20190707_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='author',
            field=models.OneToOneField(default=None, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='health',
            name='author',
            field=models.OneToOneField(default=None, on_delete=models.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
