# Generated by Django 2.0.3 on 2019-07-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20190707_0725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='thumb',
            new_name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='general',
            name='name',
        ),
        migrations.RemoveField(
            model_name='health',
            name='name',
        ),
    ]
