# Generated by Django 2.0.3 on 2019-07-11 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20190707_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to State', 'Prefer Not to State')], max_length=200),
        ),
    ]
