# Generated by Django 2.0.3 on 2019-10-26 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_friend_current_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
