# Generated by Django 2.0.3 on 2019-10-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_auto_20191026_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to State', 'Prefer Not to State')], max_length=200),
        ),
    ]
