# Generated by Django 3.0.6 on 2020-07-23 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20200615_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='group',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='health',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to State', 'Prefer Not to State')], max_length=200),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
