# Generated by Django 3.0.6 on 2020-07-23 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0025_auto_20200723_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='age',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
