# Generated by Django 3.0.6 on 2020-07-23 15:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0027_auto_20200723_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='general',
            name='group',
            field=models.IntegerField(blank=True, error_messages={'group': 'The group requirement is between 2 and 20.'}, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='health',
            name='age',
            field=models.IntegerField(error_messages={'age': 'The age requirement is between 17 and 80 years old.'}, validators=[django.core.validators.MinValueValidator(17), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='health',
            name='weight',
            field=models.IntegerField(blank=True, error_messages={'weight': 'The weight requirement is between 50lbs and 500lbs.'}, validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
