# Generated by Django 3.0.6 on 2020-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_auto_20200723_1041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='general',
            name='group',
        ),
        migrations.RemoveField(
            model_name='general',
            name='often',
        ),
        migrations.RemoveField(
            model_name='health',
            name='fit',
        ),
        migrations.RemoveField(
            model_name='health',
            name='goal',
        ),
        migrations.RemoveField(
            model_name='health',
            name='location',
        ),
        migrations.RemoveField(
            model_name='health',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='health',
            name='weight',
        ),
        migrations.AddField(
            model_name='general',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='general',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='general',
            name='thumbnail',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='health',
            name='exercise',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='health',
            name='food',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='health',
            name='mental',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='health',
            name='sleep',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='health',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer Not to State', 'Prefer Not to State')], default=None, max_length=200),
        ),
    ]
