# Generated by Django 3.0.6 on 2020-12-19 00:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_auto_20201211_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='health',
            name='age',
            field=models.IntegerField(error_messages={'age': 'The age requirement is between 18 and 80 years old.'}, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(80)]),
        ),
    ]
