# Generated by Django 2.0.3 on 2019-05-03 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GENDER_CHOICES',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Health_Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('Female', 'Female'), ('Male', 'Male'), ('Neither', 'Prefer Not to State')], max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='gender_choices',
            name='theGender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Health_Info'),
        ),
    ]
