# Generated by Django 2.0.3 on 2019-05-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gender_choices',
            name='theGender',
        ),
        migrations.DeleteModel(
            name='GENDER_CHOICES',
        ),
        migrations.DeleteModel(
            name='Health_Info',
        ),
    ]
